// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Telegrams.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Telegrams {

  /// <summary>Holder for reflection information generated from Telegrams.proto</summary>
  public static partial class TelegramsReflection {

    #region Descriptor
    /// <summary>File descriptor for Telegrams.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TelegramsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9UZWxlZ3JhbXMucHJvdG8SCVRlbGVncmFtcyKgAgoHUmVxdWVzdBIWCg50",
            "cmFuc2FjdGlvbl9pZBgBIAEoCRIrCgdjb21tYW5kGAIgASgOMhouVGVsZWdy",
            "YW1zLlJlcXVlc3QuQ29tbWFuZBIPCgdtZXNzYWdlGAMgASgJEhIKCnRyYWlu",
            "aW5nX3gYBCADKAISEgoKdHJhaW5pbmdfeRgFIAMoAhIRCglwcmVkaWN0X3gY",
            "BiADKAISFAoMcHJlZGljdGlvbl95GAcgAygCIm4KB0NvbW1hbmQSCQoFUFJJ",
            "TlQQABISCg5CRUdJTl9UUkFJTklORxABEhUKEUFERF9UUkFJTklOR19EQVRB",
            "EAISEAoMRU5EX1RSQUlOSU5HEAMSCwoHUFJFRElDVBAEEg4KClBSRURJQ1RJ",
            "T04QBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Telegrams.Request), global::Telegrams.Request.Parser, new[]{ "TransactionId", "Command", "Message", "TrainingX", "TrainingY", "PredictX", "PredictionY" }, null, new[]{ typeof(global::Telegrams.Request.Types.Command) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Telegrams.TelegramsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      transactionId_ = other.transactionId_;
      command_ = other.command_;
      message_ = other.message_;
      trainingX_ = other.trainingX_.Clone();
      trainingY_ = other.trainingY_.Clone();
      predictX_ = other.predictX_.Clone();
      predictionY_ = other.predictionY_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "transaction_id" field.</summary>
    public const int TransactionIdFieldNumber = 1;
    private string transactionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransactionId {
      get { return transactionId_; }
      set {
        transactionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    private global::Telegrams.Request.Types.Command command_ = global::Telegrams.Request.Types.Command.Print;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Telegrams.Request.Types.Command Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "training_x" field.</summary>
    public const int TrainingXFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_trainingX_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> trainingX_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> TrainingX {
      get { return trainingX_; }
    }

    /// <summary>Field number for the "training_y" field.</summary>
    public const int TrainingYFieldNumber = 5;
    private static readonly pb::FieldCodec<float> _repeated_trainingY_codec
        = pb::FieldCodec.ForFloat(42);
    private readonly pbc::RepeatedField<float> trainingY_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> TrainingY {
      get { return trainingY_; }
    }

    /// <summary>Field number for the "predict_x" field.</summary>
    public const int PredictXFieldNumber = 6;
    private static readonly pb::FieldCodec<float> _repeated_predictX_codec
        = pb::FieldCodec.ForFloat(50);
    private readonly pbc::RepeatedField<float> predictX_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> PredictX {
      get { return predictX_; }
    }

    /// <summary>Field number for the "prediction_y" field.</summary>
    public const int PredictionYFieldNumber = 7;
    private static readonly pb::FieldCodec<float> _repeated_predictionY_codec
        = pb::FieldCodec.ForFloat(58);
    private readonly pbc::RepeatedField<float> predictionY_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> PredictionY {
      get { return predictionY_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TransactionId != other.TransactionId) return false;
      if (Command != other.Command) return false;
      if (Message != other.Message) return false;
      if(!trainingX_.Equals(other.trainingX_)) return false;
      if(!trainingY_.Equals(other.trainingY_)) return false;
      if(!predictX_.Equals(other.predictX_)) return false;
      if(!predictionY_.Equals(other.predictionY_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TransactionId.Length != 0) hash ^= TransactionId.GetHashCode();
      if (Command != global::Telegrams.Request.Types.Command.Print) hash ^= Command.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      hash ^= trainingX_.GetHashCode();
      hash ^= trainingY_.GetHashCode();
      hash ^= predictX_.GetHashCode();
      hash ^= predictionY_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TransactionId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TransactionId);
      }
      if (Command != global::Telegrams.Request.Types.Command.Print) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Command);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      trainingX_.WriteTo(output, _repeated_trainingX_codec);
      trainingY_.WriteTo(output, _repeated_trainingY_codec);
      predictX_.WriteTo(output, _repeated_predictX_codec);
      predictionY_.WriteTo(output, _repeated_predictionY_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TransactionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransactionId);
      }
      if (Command != global::Telegrams.Request.Types.Command.Print) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      size += trainingX_.CalculateSize(_repeated_trainingX_codec);
      size += trainingY_.CalculateSize(_repeated_trainingY_codec);
      size += predictX_.CalculateSize(_repeated_predictX_codec);
      size += predictionY_.CalculateSize(_repeated_predictionY_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.TransactionId.Length != 0) {
        TransactionId = other.TransactionId;
      }
      if (other.Command != global::Telegrams.Request.Types.Command.Print) {
        Command = other.Command;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      trainingX_.Add(other.trainingX_);
      trainingY_.Add(other.trainingY_);
      predictX_.Add(other.predictX_);
      predictionY_.Add(other.predictionY_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TransactionId = input.ReadString();
            break;
          }
          case 16: {
            Command = (global::Telegrams.Request.Types.Command) input.ReadEnum();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
          case 34:
          case 37: {
            trainingX_.AddEntriesFrom(input, _repeated_trainingX_codec);
            break;
          }
          case 42:
          case 45: {
            trainingY_.AddEntriesFrom(input, _repeated_trainingY_codec);
            break;
          }
          case 50:
          case 53: {
            predictX_.AddEntriesFrom(input, _repeated_predictX_codec);
            break;
          }
          case 58:
          case 61: {
            predictionY_.AddEntriesFrom(input, _repeated_predictionY_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Command {
        [pbr::OriginalName("PRINT")] Print = 0,
        [pbr::OriginalName("BEGIN_TRAINING")] BeginTraining = 1,
        [pbr::OriginalName("ADD_TRAINING_DATA")] AddTrainingData = 2,
        [pbr::OriginalName("END_TRAINING")] EndTraining = 3,
        [pbr::OriginalName("PREDICT")] Predict = 4,
        [pbr::OriginalName("PREDICTION")] Prediction = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
